# basic
title: Daily
subtitle: Minimalism, simplicity and refined details
favicon: /images/favicon.ico

avatar: //7oxhwl.com1.z0.glb.clouddn.com/image/Logo.png
# banner_small: images/banner-small.png
# banner_large: images/banner-large.png
logo: //7oxhwl.com1.z0.glb.clouddn.com/image/Logo.png

# disqus
#disqus_shortname: drakeleung

highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# nav #
nav:
  Home: .
  Archive: archives
  Books: books.html
  Links: links.html
  About: about.html
  # rss: atom.xml

# hexo-renderer-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false

# Default post title
default_post_title: Untitled

# social
social:
  github: https://github.com/panjunwen
  weibo: http://t.qq.com/junwen-pan
  mail: i@panjunwen.com
  # twitter: https://twitter.com/GallenHu

# disqus_shortname: junwens

# widget
#   title: 标题
#   content: 内容
widget:
  title: ABOUT
  content: Deserts的博客<br/><br/>记录我的所学所见所想

footer: Powered by <a href="https://hexo.io/" target="_blank">Hexo</a> with Theme <a href="https://github.com/GallenHu/hexo-theme-Daily" target="_blank">Daily</a>
